version: "3.3"
services:
  api:
    image: lexikon:0.0.1
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test
      REDIS_HOST: redis
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test
  redis:
    image: redis:alpine